workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemagic

    scripts:
      - name: Fetch signing files
        script: |
          xcode-project use-profiles --type app-store

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "HelloWorld.xcodeproj" \
            --scheme "HelloWorld" \
            --export-method app-store

    artifacts:
      - $CM_BUILD_DIR/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        api_key: codemagic   # 👈 explicitly point at the integration
        submit_to_testflight: true