workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        XCODE_PROJECT: HelloWorld.xcodeproj
        XCODE_SCHEME: HelloWorld
      xcode: latest
      cocoapods: default

    scripts:
      - name: Fetch signing files (automatic)
        script: |
          app-store-connect fetch-signing-files "com.disquietous.HelloWorld" \
            --platform IOS \
            --type IOS_APP_STORE \
            --create
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

      - name: Build iOS app
        script: |
          # Build and archive
          xcodebuild -project $XCODE_PROJECT \
                     -scheme $XCODE_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     archive \
                     -archivePath $CM_BUILD_DIR/HelloWorld.xcarchive \
                     -allowProvisioningUpdates \
                     DEVELOPMENT_TEAM=$CM_DEVELOPER_TEAM \
                     CODE_SIGN_STYLE=Automatic

          # Export IPA
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/HelloWorld.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true