workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120

    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: HelloWorld.xcodeproj
        XCODE_SCHEME: HelloWorld

    scripts:
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - $CM_BUILD_DIR/*.ipa

    integrations:
      app_store_connect: codemagic

    code_signing:
      xcode: automatic

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true