workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: HelloWorld.xcodeproj
        XCODE_SCHEME: HelloWorld
      xcode: latest
      cocoapods: default

    scripts:
      - name: Build iOS app
        script: |
          # Let Codemagic manage provisioning automatically
          xcode-project use-profiles

          # Build and archive
          xcodebuild -project $XCODE_PROJECT \
                     -scheme $XCODE_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     archive \
                     -archivePath $CM_BUILD_DIR/HelloWorld.xcarchive \
                     -allowProvisioningUpdates

          # Export IPA (Codemagic will handle ExportOptions automatically)
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/HelloWorld.xcarchive \
                     -exportPath $CM_BUILD_DIR \
                     -allowProvisioningUpdates

    artifacts:
      - $CM_BUILD_DIR/*.ipa

    code_signing:
      ios:
        distribution_type: app_store
        bundle_identifier: "com.disquietous.HelloWorld"
        provisioning_profiles: automatic

    publishing:
      app_store_connect:
        credentials: codemagic   # 👈 matches your API key name
        submit_to_testflight: true
