workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemagic

    environment:
      vars:
        XCODE_PROJECT: HelloWorld.xcodeproj
        XCODE_SCHEME: HelloWorld
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.disquietous.HelloWorld   # 👈 required

    scripts:
      - name: Fetch signing files
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
        api_key: codemagic
        submit_to_testflight: true