workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        XCODE_PROJECT: HelloWorld.xcodeproj
        XCODE_SCHEME: HelloWorld
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS app
        script: |
          # Build and archive
          xcodebuild -project $XCODE_PROJECT \
                     -scheme $XCODE_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/HelloWorld.xcarchive

          # Export IPA
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/HelloWorld.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
